[versions]
bouncycastle = "1.83"
junit-jupiter = "6.0.2"
slf4j = "2.0.17"
teavm = "0.13.0"

[libraries]
bouncycastle-bcpg = { module = "org.bouncycastle:bcpg-jdk18on", version.ref = "bouncycastle" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
teavm-core = { module = "org.teavm:teavm-core", version.ref = "teavm" }
teavm-jso-apis = { module = "org.teavm:teavm-jso-apis", version.ref = "teavm" }

[plugins]
teavm = { id = "org.teavm", version.ref = "teavm" }
